#!/bin/bash

DATETIME=$(date +"%Y-%m-%d--%H-%M-%S")

# Make parameter directory
mkdir -p ./benches/parameters

echo ALL BENCHES

# Specify number of warmup and measurement runs
echo 1 > ./benches/parameters/n_warmup
echo 10 > ./benches/parameters/n_measure

# For all benches
for r in 32 64 128 256 512 1024
do
    # Make output directory
    mkdir -p ./results/raw/additional_benches/r_$r

    # Write parameters
    echo 8 > ./benches/parameters/input_bytes
    echo 8 > ./benches/parameters/gamma_bytes
    echo 8 > ./benches/parameters/time_bytes
    echo 4 > ./benches/parameters/mt_depth
    echo $r > ./benches/parameters/randomness_bytes

    echo r=$r

    # Run benches
    echo "Running base_histogram [1/6]"
    cargo bench --bench base_histogram --features print-trace > ./results/raw/additional_benches/r_$r/"${DATETIME}"_bench_base_histogram.txt 2>&1

    echo "Running expand_histogram [2/6]"
    cargo bench --bench expand_histogram --features print-trace > ./results/raw/additional_benches/r_$r/"${DATETIME}"_bench_expand_histogram.txt 2>&1

    echo "Running shuffle_histogram [3/6]"
    cargo bench --bench shuffle_histogram --features print-trace > ./results/raw/additional_benches/r_$r/"${DATETIME}"_bench_shuffle_histogram.txt 2>&1

    echo "Running base_real [4/6]"
    cargo bench --bench base_real --features print-trace > ./results/raw/additional_benches/r_$r/"${DATETIME}"_bench_base_real.txt 2>&1

    echo "Running expand_real [5/6]"
    cargo bench --bench expand_real --features print-trace > ./results/raw/additional_benches/r_$r/"${DATETIME}"_bench_expand_real.txt 2>&1

    echo "Running shuffle_real [6/6]"
    cargo bench --bench shuffle_real --features print-trace > ./results/raw/additional_benches/r_$r/"${DATETIME}"_bench_shuffle_real.txt 2>&1

    # Clear parameters
    rm ./benches/parameters/input_bytes
    rm ./benches/parameters/gamma_bytes
    rm ./benches/parameters/time_bytes
    rm ./benches/parameters/mt_depth
    rm ./benches/parameters/randomness_bytes
done

echo EXPAND BENCHES ONLY

# Expand benches only
for m in 2 3 4 5 6 7 8 9 10 11
do

    # Make output directory
    mkdir -p ./results/raw/additional_benches/m_$m

    # Write parameters
    echo 8 > ./benches/parameters/input_bytes
    echo 8 > ./benches/parameters/gamma_bytes
    echo 8 > ./benches/parameters/time_bytes
    echo $m > ./benches/parameters/mt_depth

    echo m=$m

    # Run benches

    echo 16 > ./benches/parameters/randomness_bytes

    echo "Running expand_histogram [1/2]"
    cargo bench --bench expand_histogram --features print-trace > ./results/raw/additional_benches/m_$m/"${DATETIME}"_bench_expand_histogram.txt 2>&1

    rm ./benches/parameters/randomness_bytes
    echo 24 > ./benches/parameters/randomness_bytes

    echo "Running expand_real [2/2]"
    cargo bench --bench expand_real --features print-trace > ./results/raw/additional_benches/m_$m/"${DATETIME}"_bench_expand_real.txt 2>&1

    # Clear parameters
    rm ./benches/parameters/input_bytes
    rm ./benches/parameters/gamma_bytes
    rm ./benches/parameters/time_bytes
    rm ./benches/parameters/mt_depth
    rm ./benches/parameters/randomness_bytes
done

# Remove parameter directory
rm -rf ./benches/parameters

echo Parsing results
python ./scripts/parse_additional_bench_results.py "${DATETIME}"

echo Making plots
python ./scripts/make_plots.py "${DATETIME}"